apiVersion: apps/v1
kind: Deployment
metadata:
  name: asterisk
  namespace: voip
  labels:
    app: asterisk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asterisk
  template:
    metadata:
      name: asterisk
      labels:
        app: asterisk
    spec:
      containers:
      - name: asterisk
        image : flpmarcos/asterisk13-centos
        # volumeMounts:
        #   - name: config
        #     mountPath: /etc/asterisk
        #   - name: config
        #     mountPath: /var/log/asterisk
        #   - name: config
        #     mountPath: /var/spool/asterisk
        #   - name: config
        #     mountPath: /var/lib/asterisk/sounds
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ASTERISK_USER
          value: root
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 5060
          name: sip
          protocol: UDP
        - containerPort: 5038
          name: ami
          protocol: TCP
        - containerPort: 10000
          name: trafego00
          protocol: UDP
        - containerPort: 10001
          name: trafego01
          protocol: UDP
        - containerPort: 10002
          name: trafego02
          protocol: UDP
        - containerPort: 10003
          name: trafego03
          protocol: UDP
        - containerPort: 10004
          name: trafego04
          protocol: UDP
        - containerPort: 10005
          name: trafego05
          protocol: UDP
        - containerPort: 10006
          name: trafego06
          protocol: UDP
        - containerPort: 10007
          name: trafego07
          protocol: UDP
        - containerPort: 10008
          name: trafego08
          protocol: UDP
        - containerPort: 10009
          name: trafego09
          protocol: UDP
        - containerPort: 10010
          name: trafego10
          protocol: UDP
      volumes:
        - name: config
          emptyDir: {}
