kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# - role: control-plane
#   extraPortMappings:
#   - containerPort: 32000
#     hostPort: 32000
#     listenAddress: "127.0.0.1"
#     protocol: TCP
#   - containerPort: 30000
#     hostPort: 30000
#     listenAddress: "127.0.0.1"
#     protocol: TCP
#   - containerPort: 31000
#     hostPort: 31000
#     listenAddress: "127.0.0.1"
#     protocol: TCP
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
# - role: control-plane
# - role: control-plane
- role: worker
- role: worker
- role: worker
